### ISSUE TITLE
不明白自定义协议

### ISSUE THREAD

**Issue by yaoxiaofeng1989** [imRainChen/Mega-Wechat#1]
你的协议看不懂，我想自己写个client然后封装数据发送，能给个简单的demo吗？

**Comment by imRainChen** [comment]
可以的。你也可以看看我写的[Mega-WeChat-Client](https://github.com/imRainChen/Mega-WeChat-Client)，里面有详细的实现

**Comment by yaoxiaofeng1989** [comment]
就是按照你client项目里的代码写的一个client端，发送数据后，server端onreceive始终触发不了，后来发现你wechat.ini里的参数写错，open_eof_check    应该是open_length_check

**Comment by imRainChen** [comment]
感谢发现这个错误，我去修改下
