### ISSUE TITLE
Swoole\Client::recv(): recv() failed. Error: Resource temporarily unavailable [11]

### ISSUE THREAD

**Issue by heaven2358** [imRainChen/Mega-Wechat#2]
使用test/SetTableCommandTest.php测试返回Error: Resource temporarily unavailable [11]
使用[mega-Client](https://github.com/imRainChen/Mega-WeChat-Client) 项目，添加或更新模板也会报这个错误。抓包截图如下

![image](https://user-images.githubusercontent.com/4520702/31220543-5ea0ccca-a986-11e7-8f79-de06451fffe1.png)

**Comment by hezll** [comment]
这个问题解决了么，我也出现这个问题了

**Comment by hezll** [comment]
1.server debug 文件中的wechat.ini需要配置正确的路径，建议不行自己建一个。可以查看swoole log 等。一般增长最大的那个  
2. shell, system 等禁止掉的函数要打开

3. client runtime下的app.log 和 mega log 能告诉你问题,config/web.php配置中的debug allow ip 改成YII_DEBUG关掉。

**Comment by hezll** [comment]
现在可以显示正在执行，但是仍然有上图的bug
![image](https://user-images.githubusercontent.com/1241715/34828216-ed1cf33c-f730-11e7-89dc-2fca0c39ea10.png)
![image](https://user-images.githubusercontent.com/1241715/34828227-fc06b838-f730-11e7-8d88-cc9fba718c5b.png)

**Comment by imRainChen** [comment]
项目很久没维护了，出现这些问题，大部分是安装高级版本的swoole框架导致的，我会在周末这两天抽空调试，请谅解。
